package com.esper.model;
import java.util.ArrayList;

// -------------------------------------------------------------------------
/**
 *  Contains all the cards from the current Standard set and a search by name
 *  function for adding the cards to the deck.
 *
 *  @author Zachary Lytle (zakpak23)
 *  @version 2012.04.16
 */
public class Database
{
    private ArrayList<Card> dataList;

    // ----------------------------------------------------------
    /**
     * On create, the database is filled with every card from the current
     * Standard set.
     */
    public Database()
    {
        dataList = new ArrayList<Card>(1181);
        dataList.add(new Card("Abattoir Ghoul", 'B', 4, 'C'));
        dataList.add(new Card("Abbey Griffin", 'W', 4, 'C'));
        dataList.add(new Card("Abuna Acolyte", 'W', 2, 'C'));
        dataList.add(new Card("Accorder Paladin", 'W', 2, 'C'));
        dataList.add(new Card("Accorder's Shield", 'A', 0, 'A'));
        dataList.add(new Card("Acid Web Spider", 'G', 5, 'C'));
        dataList.add(new Card("Acidic Slime", 'G', 5, 'C'));
        dataList.add(new Card("Act of Aggression", 'R', 5, 'I'));
        dataList.add(new Card("Act of Treason", 'R', 3, 'S'));
        dataList.add(new Card("Adaptive Automaton", 'A', 3, 'C'));
        dataList.add(new Card("Aegis Angel", 'W', 6, 'C'));
        dataList.add(new Card("AEther Adept", 'U', 3, 'C'));
        dataList.add(new Card("Afflicted Deserter/Werewolf Ransacker", 'R', 4, 'C'));
        dataList.add(new Card("Alabaster Mage", 'W', 2, 'C'));
        dataList.add(new Card("Alloy Myr", 'A', 3, 'C'));
        dataList.add(new Card("Alluring Siren", 'U', 2, 'C'));
        dataList.add(new Card("Alpha Brawl", 'R', 8, 'S'));
        dataList.add(new Card("Alpha Tyrranax", 'G', 6, 'C'));
        dataList.add(new Card("Altar of the Lost", 'A', 3, 'A'));
        dataList.add(new Card("Altar's Reap", 'B', 2, 'I'));
        dataList.add(new Card("Ambush Viper", 'G', 2, 'C'));
        dataList.add(new Card("Amphin Cutthroat", 'U', 4, 'C'));
        dataList.add(new Card("Ancient Grudge", 'R', 2, 'I'));
        dataList.add(new Card("Angel of Flight Alabaster", 'W', 5, 'C'));
        dataList.add(new Card("Angelic Destiny", 'W', 4, 'E'));
        dataList.add(new Card("Angelic Overseer", 'W', 5, 'C'));
        dataList.add(new Card("Angel's Feather", 'A', 2, 'A'));
        dataList.add(new Card("Angel's Mercy", 'W', 4, 'I'));
        dataList.add(new Card("Apostle's Blessing", 'W', 2, 'I'));
        dataList.add(new Card("Arachnus Spinner", 'G', 6, 'C'));
        dataList.add(new Card("Arachnus Web", 'G', 3, 'E'));
        dataList.add(new Card("Arbalest Elite", 'W', 4, 'C'));
        dataList.add(new Card("Arc Trail", 'R', 2, 'S'));
        dataList.add(new Card("Archangel's Light", 'W', 8, 'S'));
        dataList.add(new Card("Archon of Justice", 'W', 5, 'C'));
        dataList.add(new Card("Ardent Recruit", 'W', 1, 'C'));
        dataList.add(new Card("Argent Mutation", 'U', 3, 'I'));
        dataList.add(new Card("Argent Sphinx", 'U', 4, 'C'));
        dataList.add(new Card("Argentum Armor", 'A', 6, 'A'));
        dataList.add(new Card("Arm with AEther", 'U', 3, 'S'));
        dataList.add(new Card("Armored Skaab", 'U', 3, 'C'));
        dataList.add(new Card("Armored Warhorse", 'W', 2, 'C'));
        dataList.add(new Card("Army of the Damned", 'B', 8, 'S'));
        dataList.add(new Card("Arrest", 'W', 3, 'E'));
        dataList.add(new Card("Artful Dodge", 'U', 1, 'S'));
        dataList.add(new Card("Artillerize", 'R', 4, 'I'));
        dataList.add(new Card("Asceticism", 'G', 5, 'E'));
        dataList.add(new Card("Ashmouth Hound", 'R', 2, 'C'));
        dataList.add(new Card("Assault Griffin", 'W', 4, 'C'));
        dataList.add(new Card("Assault Strobe", 'R', 1, 'S'));
        dataList.add(new Card("Auramancer", 'W', 3, 'C'));
        dataList.add(new Card("Auriok Edgewright", 'W', 2, 'C'));
        dataList.add(new Card("Auriok Replica", 'A', 3, 'C'));
        dataList.add(new Card("Auriok Sunchaser", 'W', 2, 'C'));
        dataList.add(new Card("Auriok Survivors", 'W', 6, 'C'));
        dataList.add(new Card("Autumn's Veil", 'G', 1, 'I'));
        dataList.add(new Card("Avacynian Priest", 'W', 2, 'C'));
        dataList.add(new Card("Avacyn's Collar", 'A', 1, 'A'));
        dataList.add(new Card("Avacyn's Pilgrim", 'G', 1, 'C'));
        dataList.add(new Card("Aven Fleetwing", 'U', 4, 'C'));
        dataList.add(new Card("Azure Mage", 'U', 2, 'C'));
        dataList.add(new Card("Back from the Brink", 'U', 6, 'E'));
        dataList.add(new Card("Balefire Dragon", 'R', 7, 'C'));
        dataList.add(new Card("Banishment Decree", 'W', 5, 'I'));
        dataList.add(new Card("Bar the Door", 'W', 3, 'I'));
        dataList.add(new Card("Barbed Battlegear", 'A', 3, 'A'));
        dataList.add(new Card("Barrage Ogre", 'R', 5, 'C'));
        dataList.add(new Card("Batterskull", 'A', 5, 'A'));
        dataList.add(new Card("Battleground Geist", 'U', 5, 'C'));
        dataList.add(new Card("Beast Within", 'G', 3, 'I'));
        dataList.add(new Card("Beguiler of Wills", 'U', 5, 'C'));
        dataList.add(new Card("Bellowing Tanglewurm", 'G', 5, 'C'));
        dataList.add(new Card("Belltower Sphinx", 'U', 5, 'C'));
        dataList.add(new Card("Benalish Veteran", 'W', 3, 'C'));
        dataList.add(new Card("Birds of Paradise", 'G', 1, 'C'));
        dataList.add(new Card("Birthing Pod", 'G', 4, 'A'));
        dataList.add(new Card("Bitterheart Witch", 'B', 5, 'C'));
        dataList.add(new Card("Black Cat", 'B', 2, 'C'));
        dataList.add(new Card("Black Sun's Zenith", 'B', 2, 'S'));
        dataList.add(new Card("Blackcleave Cliffs", 'N', 0, 'L'));
        dataList.add(new Card("Blackcleave Goblin", 'B', 4, 'C'));
        dataList.add(new Card("Blade Splicer", 'W', 3, 'C'));
        dataList.add(new Card("Bladed Pinions", 'A', 2, 'A'));
        dataList.add(new Card("Bladed Sentinel", 'A', 4, 'C'));
        dataList.add(new Card("Blade-Tribe Berserkers", 'R', 4, 'C'));
        dataList.add(new Card("Blasphemous Act", 'R', 9, 'S'));
        dataList.add(new Card("Blazing Torch", 'A', 1, 'A'));
        dataList.add(new Card("Bleak Coven Vampires", 'B', 5, 'C'));
        dataList.add(new Card("Blight Mamba", 'G', 2, 'C'));
        dataList.add(new Card("Blighted Agent", 'U', 2, 'C'));
        dataList.add(new Card("Blightsteel Colossus", 'A', 12, 'C'));
        dataList.add(new Card("Blightwidow", 'G', 4, 'C'));
        dataList.add(new Card("Blind Zealot", 'B', 3, 'C'));
        dataList.add(new Card("Blinding Souleater", 'A', 3, 'C'));
        dataList.add(new Card("Blistergrub", 'B', 3, 'C'));
        dataList.add(new Card("Blisterstick Shaman", 'R', 3, 'C'));
        dataList.add(new Card("Blood Feud", 'R', 6, 'S'));
        dataList.add(new Card("Blood Ogre", 'R', 3, 'C'));
        dataList.add(new Card("Blood Seeker", 'B', 2, 'C'));
        dataList.add(new Card("Bloodcrazed Neonate", 'R', 2, 'C'));
        dataList.add(new Card("Bloodgift Demon", 'B', 5, 'C'));
        dataList.add(new Card("Bloodline Keeper/Lord of Lineage", 'B', 4, 'C'));
        dataList.add(new Card("Bloodlord of Vaasgoth", 'B', 5, 'C'));
        dataList.add(new Card("Bloodrage Vampire", 'B', 3, 'C'));
        dataList.add(new Card("Bloodshot Trainee", 'R', 4, 'C'));
        dataList.add(new Card("Bludgeon Brawl", 'R', 3, 'E'));
        dataList.add(new Card("Blue Sun's Zenith", 'U', 3, 'I'));
        dataList.add(new Card("Blunt the Assault", 'G', 4, 'I'));
        dataList.add(new Card("Bonds of Faith", 'W', 2, 'E'));
        dataList.add(new Card("Bonds of Quicksilver", 'U', 4, 'E'));
        dataList.add(new Card("Bone to Ash", 'U', 4, 'I'));
        dataList.add(new Card("Bonebreaker Giant", 'R', 5, 'C'));
        dataList.add(new Card("Bonehoard", 'A', 4, 'A'));
        dataList.add(new Card("Boneyard Wurm", 'G', 2, 'C'));
        dataList.add(new Card("Bountiful Harvest", 'G', 5, 'S'));
        dataList.add(new Card("Brain Weevil", 'B', 4, 'C'));
        dataList.add(new Card("Bramblecrush", 'G', 4, 'S'));
        dataList.add(new Card("Brass Squire", 'A', 3, 'C'));
        dataList.add(new Card("Break of Day", 'W', 2, 'I'));
        dataList.add(new Card("Briarpack Alpha", 'G', 4, 'C'));
        dataList.add(new Card("Brimstone Volley", 'R', 3, 'I'));
        dataList.add(new Card("Brindle Boar", 'G', 3, 'C'));
        dataList.add(new Card("Brink of Disaster", 'B', 4, 'E'));
        dataList.add(new Card("Brutalizer Exarch", 'G', 6, 'C'));
        dataList.add(new Card("Bump in the Night", 'B', 1, 'S'));
        dataList.add(new Card("Burden of Guilt", 'W', 1, 'E'));
        dataList.add(new Card("Buried Ruin", 'N', 0, 'L'));
        dataList.add(new Card("Burn the Impure", 'R', 2, 'I'));
        dataList.add(new Card("Burning Oil", 'R', 2, 'I'));
        dataList.add(new Card("Burning Vengeance", 'R', 3, 'E'));
        dataList.add(new Card("Butcher's Cleaver", 'A', 3, 'A'));
        dataList.add(new Card("Cackling Counterpart", 'U', 3, 'I'));
        dataList.add(new Card("Caged Sun", 'A', 6, 'A'));
        dataList.add(new Card("Call to the Grave", 'B', 5, 'E'));
        dataList.add(new Card("Call to the Kindred", 'U', 4, 'E'));
        dataList.add(new Card("Cancel", 'U', 3, 'I'));
        dataList.add(new Card("Carapace Forger", 'G', 2, 'C'));
        dataList.add(new Card("Caravan Vigil", 'G', 1, 'S'));
        dataList.add(new Card("Caress of Phyrexia", 'B', 5, 'S'));
        dataList.add(new Card("Carnage Wurm", 'G', 7, 'C'));
        dataList.add(new Card("Carnifex Demon", 'B', 6, 'C'));
        dataList.add(new Card("Carrion Call", 'G', 4, 'I'));
        dataList.add(new Card("Cathedral Membrane", 'W', 2, 'C'));
        dataList.add(new Card("Caustic Hound", 'B', 6, 'C'));
        dataList.add(new Card("Celestial Purge", 'W', 2, 'I'));
        dataList.add(new Card("Cellar Door", 'A', 2, 'A'));
        dataList.add(new Card("Cemetery Reaper", 'B', 3, 'C'));
        dataList.add(new Card("Cerebral Eruption", 'R', 4, 'S'));
        dataList.add(new Card("Chained Throatseeker", 'U', 6, 'C'));
        dataList.add(new Card("Chalice of Life/Chalice of Death", 'A', 3, 'A'));
        dataList.add(new Card("Champion of the Parish", 'W', 1, 'C'));
        dataList.add(new Card("Chancellor of the Annex", 'W', 7, 'C'));
        dataList.add(new Card("Chancellor of the Dross", 'B', 7, 'C'));
        dataList.add(new Card("Chancellor of the Forge", 'R', 7, 'C'));
        dataList.add(new Card("Chancellor of the Spires", 'U', 7, 'C'));
        dataList.add(new Card("Chancellor of the Tangle", 'G', 7, 'C'));
        dataList.add(new Card("Chandra,  the Firebrand", 'R', 4, 'P'));
        dataList.add(new Card("Chandra's Outrage", 'R', 4, 'I'));
        dataList.add(new Card("Chandra's Phoenix", 'R', 3, 'C'));
        dataList.add(new Card("Chant of the Skifsang", 'U', 3, 'E'));
        dataList.add(new Card("Chapel Geist", 'W', 3, 'C'));
        dataList.add(new Card("Charmbreaker Devils", 'R', 6, 'C'));
        dataList.add(new Card("Chasm Drake", 'U', 5, 'C'));
        dataList.add(new Card("Child of Night", 'B', 2, 'C'));
        dataList.add(new Card("Chill of Foreboding", 'U', 3, 'S'));
        dataList.add(new Card("Chimeric Mass", 'A', 0, 'A'));
        dataList.add(new Card("Choking Fumes", 'W', 3, 'I'));
        dataList.add(new Card("Chosen of Markov/Markov's Servant", 'B', 3, 'C'));
        dataList.add(new Card("Chrome Steed", 'A', 4, 'C'));
        dataList.add(new Card("Circle of Flame", 'R', 2, 'E'));
        dataList.add(new Card("Civilized Scholar/Homicidal Brute", 'M', 3, 'C'));
        dataList.add(new Card("Claustrophobia", 'U', 3, 'E'));
        dataList.add(new Card("Clifftop Retreat", 'N', 0, 'L'));
        dataList.add(new Card("Clinging Mists", 'G', 3, 'I'));
        dataList.add(new Card("Cloistered Youth/Unholy Fiend", 'M', 2, 'C'));
        dataList.add(new Card("Clone Shell", 'A', 5, 'C'));
        dataList.add(new Card("Cobbled Wings", 'A', 2, 'A'));
        dataList.add(new Card("Combust", 'R', 2, 'I'));
        dataList.add(new Card("Concussive Bolt", 'R', 5, 'S'));
        dataList.add(new Card("Consecrated Sphinx", 'U', 6, 'C'));
        dataList.add(new Card("Consume Spirit", 'B', 2, 'S'));
        dataList.add(new Card("Contagion Clasp", 'A', 2, 'A'));
        dataList.add(new Card("Contagion Engine", 'A', 6, 'A'));
        dataList.add(new Card("Contagious Nim", 'B', 3, 'C'));
        dataList.add(new Card("Contested War Zone", 'N', 0, 'L'));
        dataList.add(new Card("Conversion Chamber", 'A', 3, 'A'));
        dataList.add(new Card("Copper Carapace", 'A', 1, 'A'));
        dataList.add(new Card("Copper Myr", 'A', 2, 'C'));
        dataList.add(new Card("Copperhorn Scout", 'G', 1, 'C'));
        dataList.add(new Card("Copperline Gorge", 'N', 0, 'L'));
        dataList.add(new Card("Coral Merfolk", 'U', 2, 'C'));
        dataList.add(new Card("Core Prowler", 'A', 4, 'C'));
        dataList.add(new Card("Corpse Cur", 'A', 4, 'C'));
        dataList.add(new Card("Corpse Lunge", 'B', 3, 'I'));
        dataList.add(new Card("Corrosive Gale", 'G', 1, 'S'));
        dataList.add(new Card("Corrupted Conscience", 'U', 5, 'E'));
        dataList.add(new Card("Corrupted Harvester", 'B', 6, 'C'));
        dataList.add(new Card("Corrupted Resolve", 'U', 2, 'I'));
        dataList.add(new Card("Counterlash", 'U', 6, 'I'));
        dataList.add(new Card("Creeping Corrosion", 'G', 4, 'S'));
        dataList.add(new Card("Creeping Renaissance", 'G', 5, 'S'));
        dataList.add(new Card("Creepy Doll", 'A', 5, 'C'));
        dataList.add(new Card("Crimson Mage", 'R', 2, 'C'));
        dataList.add(new Card("Crossway Vampire", 'R', 3, 'C'));
        dataList.add(new Card("Crown of Empires", 'A', 2, 'A'));
        dataList.add(new Card("Crumbling Colossus", 'A', 5, 'C'));
        dataList.add(new Card("Crush", 'R', 1, 'I'));
        dataList.add(new Card("Crushing Vines", 'G', 3, 'I'));
        dataList.add(new Card("Cryptoplasm", 'U', 3, 'C'));
        dataList.add(new Card("Cudgel Troll", 'G', 4, 'C'));
        dataList.add(new Card("Culling Dais", 'A', 2, 'A'));
        dataList.add(new Card("Curiosity", 'U', 1, 'E'));
        dataList.add(new Card("Curse of Bloodletting", 'R', 5, 'E'));
        dataList.add(new Card("Curse of Death's Hold", 'B', 5, 'E'));
        dataList.add(new Card("Curse of Echoes", 'U', 5, 'E'));
        dataList.add(new Card("Curse of Exhaustion", 'W', 4, 'E'));
        dataList.add(new Card("Curse of Misfortunes", 'B', 5, 'E'));
        dataList.add(new Card("Curse of Oblivion", 'B', 4, 'E'));
        dataList.add(new Card("Curse of Stalked Prey", 'R', 2, 'E'));
        dataList.add(new Card("Curse of the Bloody Tome", 'U', 3, 'E'));
        dataList.add(new Card("Curse of the Nightly Hunt", 'R', 3, 'E'));
        dataList.add(new Card("Curse of the Pierced Heart", 'R', 2, 'E'));
        dataList.add(new Card("Curse of Thirst", 'B', 5, 'E'));
        dataList.add(new Card("Cystbearer", 'G', 3, 'C'));
        dataList.add(new Card("Dark Favor", 'B', 2, 'E'));
        dataList.add(new Card("Darkslick Drake", 'U', 4, 'C'));
        dataList.add(new Card("Darkslick Shores", 'N', 0, 'L'));
        dataList.add(new Card("Darksteel Axe", 'A', 1, 'A'));
        dataList.add(new Card("Darksteel Juggernaut", 'A', 5, 'C'));
        dataList.add(new Card("Darksteel Myr", 'A', 3, 'C'));
        dataList.add(new Card("Darksteel Plate", 'A', 3, 'A'));
        dataList.add(new Card("Darksteel Relic", 'A', 0, 'A'));
        dataList.add(new Card("Darksteel Sentinel", 'A', 6, 'C'));
        dataList.add(new Card("Darkthicket Wolf", 'G', 2, 'C'));
        dataList.add(new Card("Dawntreader Elk", 'G', 2, 'C'));
        dataList.add(new Card("Day of Judgment", 'W', 4, 'S'));
        dataList.add(new Card("Daybreak Ranger/Nightfall Predator", 'G', 3, 'C'));
        dataList.add(new Card("Dead Weight", 'B', 1, 'E'));
        dataList.add(new Card("Deadly Allure", 'B', 1, 'S'));
        dataList.add(new Card("Dearly Departed", 'W', 6, 'C'));
        dataList.add(new Card("Death-Hood Cobra", 'G', 2, 'C'));
        dataList.add(new Card("Deathmark", 'B', 1, 'S'));
        dataList.add(new Card("Death's Caress", 'B', 5, 'S'));
        dataList.add(new Card("Deceiver Exarch", 'U', 3, 'C'));
        dataList.add(new Card("Decimator Web", 'A', 4, 'A'));
        dataList.add(new Card("Defensive Stance", 'U', 1, 'E'));
        dataList.add(new Card("Delver of Secrets/Insectile Aberration", 'U', 1, 'C'));
        dataList.add(new Card("Dementia Bat", 'B', 5, 'C'));
        dataList.add(new Card("Demonmail Hauberk", 'A', 4, 'A'));
        dataList.add(new Card("Demon's Horn", 'A', 2, 'A'));
        dataList.add(new Card("Demystify", 'W', 1, 'I'));
        dataList.add(new Card("Deranged Assistant", 'U', 2, 'C'));
        dataList.add(new Card("Deranged Outcast", 'G', 2, 'C'));
        dataList.add(new Card("Desperate Ravings", 'R', 2, 'I'));
        dataList.add(new Card("Despise", 'B', 1, 'S'));
        dataList.add(new Card("Devil's Play", 'R', 1, 'S'));
        dataList.add(new Card("Devouring Swarm", 'B', 3, 'C'));
        dataList.add(new Card("Diabolic Tutor", 'B', 4, 'S'));
        dataList.add(new Card("Diregraf Captain", 'M', 3, 'C'));
        dataList.add(new Card("Diregraf Ghoul", 'B', 1, 'C'));
        dataList.add(new Card("Disciple of Griselbrand", 'B', 2, 'C'));
        dataList.add(new Card("Disentomb", 'B', 1, 'S'));
        dataList.add(new Card("Dismember", 'B', 3, 'I'));
        dataList.add(new Card("Dispatch", 'W', 1, 'I'));
        dataList.add(new Card("Dispense Justice", 'W', 3, 'I'));
        dataList.add(new Card("Disperse", 'U', 2, 'I'));
        dataList.add(new Card("Dissipate", 'U', 3, 'I'));
        dataList.add(new Card("Dissipation Field", 'U', 4, 'E'));
        dataList.add(new Card("Distant Memories", 'U', 4, 'S'));
        dataList.add(new Card("Distress", 'B', 2, 'S'));
        dataList.add(new Card("Divination", 'U', 3, 'S'));
        dataList.add(new Card("Divination", 'U', 3, 'S'));
        dataList.add(new Card("Divine Favor", 'W', 2, 'E'));
        dataList.add(new Card("Divine Offering", 'W', 2, 'I'));
        dataList.add(new Card("Divine Reckoning", 'W', 4, 'S'));
        dataList.add(new Card("Djinn of Wishes", 'U', 5, 'C'));
        dataList.add(new Card("Doom Blade", 'B', 2, 'I'));
        dataList.add(new Card("Doomed Traveler", 'W', 1, 'C'));
        dataList.add(new Card("Doubling Chant", 'G', 6, 'S'));
        dataList.add(new Card("Dragon's Claw", 'A', 2, 'A'));
        dataList.add(new Card("Dragonskull Summit", 'N', 0, 'L'));
        dataList.add(new Card("Dream Twist", 'U', 1, 'I'));
        dataList.add(new Card("Drifting Shade", 'B', 4, 'C'));
        dataList.add(new Card("Drogskol Captain", 'M', 3, 'C'));
        dataList.add(new Card("Drogskol Reaver", 'M', 7, 'C'));
        dataList.add(new Card("Dross Hopper", 'B', 2, 'C'));
        dataList.add(new Card("Dross Ripper", 'A', 4, 'C'));
        dataList.add(new Card("Drowned Catacomb", 'N', 0, 'L'));
        dataList.add(new Card("Druidic Satchel", 'A', 3, 'A'));
        dataList.add(new Card("Due Respect", 'W', 2, 'I'));
        dataList.add(new Card("Dungeon Geists", 'U', 4, 'C'));
        dataList.add(new Card("Dungrove Elder", 'G', 3, 'C'));
        dataList.add(new Card("Duskhunter Bat", 'B', 2, 'C'));
        dataList.add(new Card("Echo Circlet", 'A', 2, 'A'));
        dataList.add(new Card("Elbrus,  the Binding Blade/Withengar Unbound", 'M', 7, 'A'));
        dataList.add(new Card("Elder Cathar", 'W', 3, 'C'));
        dataList.add(new Card("Elder of Laurels", 'G', 3, 'C'));
        dataList.add(new Card("Elesh Norn,  Grand Cenobite", 'W', 7, 'C'));
        dataList.add(new Card("Elgaud Inquisitor", 'W', 4, 'C'));
        dataList.add(new Card("Elite Inquisitor", 'W', 2, 'C'));
        dataList.add(new Card("Elite Vanguard", 'W', 1, 'C'));
        dataList.add(new Card("Elixir of Immortality", 'A', 1, 'A'));
        dataList.add(new Card("Elspeth Tirel", 'W', 5, 'P'));
        dataList.add(new Card("Elvish Archdruid", 'G', 3, 'C'));
        dataList.add(new Card("Embersmith", 'R', 2, 'C'));
        dataList.add(new Card("Endless Ranks of the Dead", 'B', 4, 'E'));
        dataList.add(new Card("Engulfing Slagwurm", 'G', 7, 'C'));
        dataList.add(new Card("Enslave", 'B', 6, 'E'));
        dataList.add(new Card("Entomber Exarch", 'B', 4, 'C'));
        dataList.add(new Card("Erdwal Ripper", 'R', 3, 'C'));
        dataList.add(new Card("Essence of the Wild", 'G', 6, 'C'));
        dataList.add(new Card("Etched Champion", 'A', 3, 'C'));
        dataList.add(new Card("Etched Monstrosity", 'A', 5, 'C'));
        dataList.add(new Card("Evil Presence", 'B', 1, 'E'));
        dataList.add(new Card("Evil Twin", 'M', 4, 'C'));
        dataList.add(new Card("Evolving Wilds", 'N', 0, 'L'));
        dataList.add(new Card("Exclusion Ritual", 'W', 6, 'E'));
        dataList.add(new Card("Executioner's Hood", 'A', 2, 'A'));
        dataList.add(new Card("Exsanguinate", 'B', 2, 'S'));
        dataList.add(new Card("Ezuri,  Renegade Leader", 'G', 3, 'C'));
        dataList.add(new Card("Ezuri's Archers", 'G', 1, 'C'));
        dataList.add(new Card("Ezuri's Brigade", 'G', 4, 'C'));
        dataList.add(new Card("Faithless Looting", 'R', 1, 'S'));
        dataList.add(new Card("Faith's Shield", 'W', 1, 'I'));
        dataList.add(new Card("Falkenrath Aristocrat", 'M', 4, 'C'));
        dataList.add(new Card("Falkenrath Marauders", 'R', 5, 'C'));
        dataList.add(new Card("Falkenrath Noble", 'B', 4, 'C'));
        dataList.add(new Card("Falkenrath Torturer", 'B', 3, 'C'));
        dataList.add(new Card("Fallen Ferromancer", 'R', 4, 'C'));
        dataList.add(new Card("Fangren Marauder", 'G', 6, 'C'));
        dataList.add(new Card("Farbog Boneflinger", 'B', 5, 'C'));
        dataList.add(new Card("Favor of the Woods", 'G', 3, 'E'));
        dataList.add(new Card("Feed the Pack", 'G', 6, 'E'));
        dataList.add(new Card("Feeling of Dread", 'W', 2, 'I'));
        dataList.add(new Card("Feral Ridgewolf", 'R', 3, 'C'));
        dataList.add(new Card("Ferrovore", 'R', 3, 'C'));
        dataList.add(new Card("Festerhide Boar", 'G', 4, 'C'));
        dataList.add(new Card("Fiend Hunter", 'W', 3, 'C'));
        dataList.add(new Card("Fiend of the Shadows", 'B', 5, 'C'));
        dataList.add(new Card("Fiery Hellhound", 'R', 3, 'C'));
        dataList.add(new Card("Fireball", 'R', 1, 'S'));
        dataList.add(new Card("Firebreathing", 'R', 1, 'E'));
        dataList.add(new Card("Fires of Undeath", 'R', 3, 'I'));
        dataList.add(new Card("Flameblast Dragon", 'R', 6, 'C'));
        dataList.add(new Card("Flameborn Hellion", 'R', 6, 'C'));
        dataList.add(new Card("Flameborn Viron", 'R', 6, 'C'));
        dataList.add(new Card("Flashfreeze", 'U', 2, 'I'));
        dataList.add(new Card("Flayer Husk", 'A', 1, 'A'));
        dataList.add(new Card("Flayer of the Hatebound", 'R', 6, 'C'));
        dataList.add(new Card("Flensermite", 'B', 2, 'C'));
        dataList.add(new Card("Flesh Allergy", 'B', 4, 'S'));
        dataList.add(new Card("Flesh-Eater Imp", 'B', 4, 'C'));
        dataList.add(new Card("Flight", 'U', 1, 'E'));
        dataList.add(new Card("Flight Spellbomb", 'A', 1, 'A'));
        dataList.add(new Card("Fling", 'R', 2, 'I'));
        dataList.add(new Card("Fling", 'R', 2, 'I'));
        dataList.add(new Card("Fog", 'G', 1, 'I'));
        dataList.add(new Card("Forbidden Alchemy", 'U', 3, 'I'));
        dataList.add(new Card("Forced Worship", 'W', 2, 'E'));
        dataList.add(new Card("Forest", 'N', 0, 'L'));
        dataList.add(new Card("Forge Devil", 'R', 1, 'C'));
        dataList.add(new Card("Fortress Crab", 'U', 4, 'C'));
        dataList.add(new Card("Frantic Salvage", 'W', 4, 'I'));
        dataList.add(new Card("Fresh Meat", 'G', 4, 'I'));
        dataList.add(new Card("Frightful Delusion", 'U', 3, 'I'));
        dataList.add(new Card("Frost Breath", 'U', 3, 'I'));
        dataList.add(new Card("Frost Titan", 'U', 6, 'C'));
        dataList.add(new Card("Fuel for the Cause", 'U', 4, 'I'));
        dataList.add(new Card("Fulgent Distraction", 'W', 3, 'I'));
        dataList.add(new Card("Full Moon's Rise", 'G', 2, 'E'));
        dataList.add(new Card("Fume Spitter", 'B', 1, 'C'));
        dataList.add(new Card("Furnace Celebration", 'R', 3, 'E'));
        dataList.add(new Card("Furnace Scamp", 'R', 1, 'C'));
        dataList.add(new Card("Furor of the Bitten", 'R', 1, 'E'));
        dataList.add(new Card("Furyborn Hellkite", 'R', 7, 'C'));
        dataList.add(new Card("Gallows Warden", 'W', 5, 'C'));
        dataList.add(new Card("Galvanic Blast", 'R', 1, 'I'));
        dataList.add(new Card("Galvanic Juggernaut", 'A', 4, 'C'));
        dataList.add(new Card("Galvanoth", 'R', 5, 'C'));
        dataList.add(new Card("Garruk Relentless/Garruk,  the Veil-Cursed", 'M', 4, 'P'));
        dataList.add(new Card("Garruk,  Primal Hunter", 'G', 5, 'P'));
        dataList.add(new Card("Garruk's Companion", 'G', 2, 'C'));
        dataList.add(new Card("Garruk's Horde", 'G', 7, 'C'));
        dataList.add(new Card("Gather the Townsfolk", 'W', 2, 'S'));
        dataList.add(new Card("Gatstaf Shepherd/Gatstaf Howler", 'G', 2, 'C'));
        dataList.add(new Card("Gavony Ironwright", 'W', 3, 'C'));
        dataList.add(new Card("Gavony Township", 'N', 0, 'L'));
        dataList.add(new Card("Geist of Saint Traft", 'M', 3, 'C'));
        dataList.add(new Card("Geistcatcher's Rig", 'A', 6, 'C'));
        dataList.add(new Card("Geistflame", 'R', 1, 'I'));
        dataList.add(new Card("Geist-Honored Monk", 'W', 5, 'C'));
        dataList.add(new Card("Genesis Wave", 'G', 3, 'S'));
        dataList.add(new Card("Geosurge", 'R', 4, 'S'));
        dataList.add(new Card("Geralf's Messenger", 'B', 3, 'C'));
        dataList.add(new Card("Geralf's Mindcrusher", 'U', 6, 'C'));
        dataList.add(new Card("Geth,  Lord of the Vault", 'B', 6, 'C'));
        dataList.add(new Card("Geth's Verdict", 'B', 2, 'I'));
        dataList.add(new Card("Ghalma's Warden", 'W', 4, 'C'));
        dataList.add(new Card("Ghost Quarter", 'N', 0, 'L'));
        dataList.add(new Card("Ghostly Possession", 'W', 3, 'E'));
        dataList.add(new Card("Ghoulcaller's Bell", 'A', 1, 'A'));
        dataList.add(new Card("Ghoulcaller's Chant", 'B', 1, 'S'));
        dataList.add(new Card("Ghoulraiser", 'B', 3, 'C'));
        dataList.add(new Card("Ghoultree", 'G', 8, 'C'));
        dataList.add(new Card("Giant Spider", 'G', 4, 'C'));
        dataList.add(new Card("Gideon Jura", 'W', 5, 'P'));
        dataList.add(new Card("Gideon's Avenger", 'W', 3, 'C'));
        dataList.add(new Card("Gideon's Lawkeeper", 'W', 1, 'C'));
        dataList.add(new Card("Gitaxian Probe", 'U', 1, 'S'));
        dataList.add(new Card("Glacial Fortress", 'N', 0, 'L'));
        dataList.add(new Card("Gladecover Scout", 'G', 1, 'C'));
        dataList.add(new Card("Glimmerpoint Stag", 'W', 4, 'C'));
        dataList.add(new Card("Glimmerpost", 'N', 0, 'L'));
        dataList.add(new Card("Glint Hawk", 'W', 1, 'C'));
        dataList.add(new Card("Glint Hawk Idol", 'A', 2, 'A'));
        dataList.add(new Card("Glissa,  the Traitor", 'M', 3, 'C'));
        dataList.add(new Card("Glissa's Courier", 'G', 3, 'C'));
        dataList.add(new Card("Glissa's Scorn", 'G', 2, 'I'));
        dataList.add(new Card("Glistener Elf", 'G', 1, 'C'));
        dataList.add(new Card("Glistening Oil", 'B', 2, 'E'));
        dataList.add(new Card("Gnathosaur", 'R', 6, 'C'));
        dataList.add(new Card("Gnaw to the Bone", 'G', 3, 'I'));
        dataList.add(new Card("Go for the Throat", 'B', 2, 'I'));
        dataList.add(new Card("Goblin Arsonist", 'R', 1, 'C'));
        dataList.add(new Card("Goblin Bangchuckers", 'R', 4, 'C'));
        dataList.add(new Card("Goblin Chieftain", 'R', 3, 'C'));
        dataList.add(new Card("Goblin Fireslinger", 'R', 1, 'C'));
        dataList.add(new Card("Goblin Gaveleer", 'R', 1, 'C'));
        dataList.add(new Card("Goblin Grenade", 'R', 1, 'S'));
        dataList.add(new Card("Goblin Piker", 'R', 2, 'C'));
        dataList.add(new Card("Goblin Tunneler", 'R', 2, 'C'));
        dataList.add(new Card("Goblin War Paint", 'R', 2, 'E'));
        dataList.add(new Card("Goblin Wardriver", 'R', 2, 'C'));
        dataList.add(new Card("Gold Myr", 'A', 2, 'C'));
        dataList.add(new Card("Golden Urn", 'A', 1, 'A'));
        dataList.add(new Card("Golem Artisan", 'A', 5, 'C'));
        dataList.add(new Card("Golem Foundry", 'A', 3, 'A'));
        dataList.add(new Card("Golem's Heart", 'A', 2, 'A'));
        dataList.add(new Card("Gore Vassal", 'W', 3, 'C'));
        dataList.add(new Card("Gorehorn Minotaurs", 'R', 4, 'C'));
        dataList.add(new Card("Grafdigger's Cage", 'A', 1, 'A'));
        dataList.add(new Card("Grafted Exoskeleton", 'A', 4, 'A'));
        dataList.add(new Card("Grand Abolisher", 'W', 2, 'C'));
        dataList.add(new Card("Grand Architect", 'U', 3, 'C'));
        dataList.add(new Card("Grasp of Darkness", 'B', 2, 'I'));
        dataList.add(new Card("Grasp of Phantoms", 'U', 4, 'S'));
        dataList.add(new Card("Grave Bramble", 'G', 3, 'C'));
        dataList.add(new Card("Grave Titan", 'B', 6, 'C'));
        dataList.add(new Card("Gravecrawler", 'B', 1, 'C'));
        dataList.add(new Card("Gravedigger", 'B', 4, 'C'));
        dataList.add(new Card("Gravepurge", 'B', 3, 'I'));
        dataList.add(new Card("Gravetiller Wurm", 'G', 6, 'C'));
        dataList.add(new Card("Graveyard Shovel", 'A', 2, 'A'));
        dataList.add(new Card("Greater Basilisk", 'G', 5, 'C'));
        dataList.add(new Card("Greatsword", 'A', 3, 'A'));
        dataList.add(new Card("Green Sun's Zenith", 'G', 1, 'S'));
        dataList.add(new Card("Greenhilt Trainee", 'G', 4, 'C'));
        dataList.add(new Card("Gremlin Mine", 'A', 1, 'A'));
        dataList.add(new Card("Griffin Rider", 'W', 2, 'C'));
        dataList.add(new Card("Griffin Sentinel", 'W', 3, 'C'));
        dataList.add(new Card("Grim Affliction", 'B', 3, 'I'));
        dataList.add(new Card("Grim Backwoods", 'N', 0, 'L'));
        dataList.add(new Card("Grim Flowering", 'G', 6, 'S'));
        dataList.add(new Card("Grim Lavamancer", 'R', 1, 'C'));
        dataList.add(new Card("Grimgrin,  Corpse-Born", 'M', 5, 'C'));
        dataList.add(new Card("Grimoire of the Dead", 'A', 4, 'A'));
        dataList.add(new Card("Grindclock", 'A', 2, 'A'));
        dataList.add(new Card("Griptide", 'U', 4, 'I'));
        dataList.add(new Card("Grizzled Outcasts/Krallenhorde Wantons", 'G', 5, 'C'));
        dataList.add(new Card("Gruesome Deformity", 'B', 1, 'E'));
        dataList.add(new Card("Gruesome Discovery", 'B', 4, 'S'));
        dataList.add(new Card("Gruesome Encore", 'B', 3, 'S'));
        dataList.add(new Card("Guardians' Pledge", 'W', 3, 'I'));
        dataList.add(new Card("Gust-Skimmer", 'A', 2, 'C'));
        dataList.add(new Card("Gut Shot", 'R', 1, 'I'));
        dataList.add(new Card("Gutter Grime", 'G', 5, 'E'));
        dataList.add(new Card("Halt Order", 'U', 3, 'I'));
        dataList.add(new Card("Hamlet Captain", 'G', 2, 'C'));
        dataList.add(new Card("Hand of the Praetors", 'B', 4, 'C'));
        dataList.add(new Card("Hanweir Watchkeep/Bane of Hanweir", 'R', 3, 'C'));
        dataList.add(new Card("Harbor Serpent", 'U', 6, 'C'));
        dataList.add(new Card("Harrowing Journey", 'B', 5, 'S'));
        dataList.add(new Card("Harvest Pyre", 'R', 2, 'I'));
        dataList.add(new Card("Haunted Fengraf", 'N', 0, 'L'));
        dataList.add(new Card("Havengul Lich", 'M', 5, 'C'));
        dataList.add(new Card("Havengul Runebinder", 'U', 4, 'C'));
        dataList.add(new Card("Headless Skaab", 'U', 3, 'C'));
        dataList.add(new Card("Heartless Summoning", 'B', 2, 'E'));
        dataList.add(new Card("Heavy Arbalest", 'A', 3, 'A'));
        dataList.add(new Card("Heavy Mattock", 'A', 3, 'A'));
        dataList.add(new Card("Heckling Fiends", 'R', 3, 'C'));
        dataList.add(new Card("Hellkite Igniter", 'R', 7, 'C'));
        dataList.add(new Card("Hellrider", 'R', 4, 'C'));
        dataList.add(new Card("Helvault", 'A', 3, 'A'));
        dataList.add(new Card("Heretic's Punishment", 'R', 5, 'E'));
        dataList.add(new Card("Hero of Bladehold", 'W', 4, 'C'));
        dataList.add(new Card("Hero of Oxid Ridge", 'R', 4, 'C'));
        dataList.add(new Card("Hex Parasite", 'A', 1, 'C'));
        dataList.add(new Card("Hexplate Golem", 'A', 7, 'C'));
        dataList.add(new Card("Hideous Visage", 'B', 3, 'S'));
        dataList.add(new Card("Highborn Ghoul", 'B', 2, 'C'));
        dataList.add(new Card("Hinterland Harbor", 'N', 0, 'L'));
        dataList.add(new Card("Hinterland Hermit/Hinterland Scourge", 'R', 2, 'C'));
        dataList.add(new Card("Hoard-Smelter Dragon", 'R', 6, 'C'));
        dataList.add(new Card("Hollowhenge Beast", 'G', 5, 'C'));
        dataList.add(new Card("Hollowhenge Scavenger", 'G', 5, 'C'));
        dataList.add(new Card("Hollowhenge Spirit", 'W', 4, 'C'));
        dataList.add(new Card("Honor of the Pure", 'W', 2, 'E'));
        dataList.add(new Card("Horizon Spellbomb", 'A', 1, 'A'));
        dataList.add(new Card("Horrifying Revelation", 'B', 1, 'S'));
        dataList.add(new Card("Hovermyr", 'A', 2, 'C'));
        dataList.add(new Card("Hunger of the Howlpack", 'G', 1, 'I'));
        dataList.add(new Card("Hunter's Insight", 'G', 3, 'I'));
        dataList.add(new Card("Huntmaster of the Fells/Ravager of the Fells", 'M', 4, 'C'));
        dataList.add(new Card("Hysterical Blindness", 'U', 3, 'I'));
        dataList.add(new Card("Ice Cage", 'U', 2, 'E'));
        dataList.add(new Card("Ichor Explosion", 'B', 7, 'S'));
        dataList.add(new Card("Ichor Rats", 'B', 3, 'C'));
        dataList.add(new Card("Ichor Wellspring", 'A', 2, 'A'));
        dataList.add(new Card("Ichorclaw Myr", 'A', 2, 'C'));
        dataList.add(new Card("Immerwolf", 'M', 3, 'C'));
        dataList.add(new Card("Immolating Souleater", 'A', 2, 'C'));
        dataList.add(new Card("Impaler Shrike", 'U', 4, 'C'));
        dataList.add(new Card("Incinerate", 'R', 2, 'I'));
        dataList.add(new Card("Increasing Ambition", 'B', 5, 'S'));
        dataList.add(new Card("Increasing Confusion", 'U', 1, 'S'));
        dataList.add(new Card("Increasing Devotion", 'W', 5, 'S'));
        dataList.add(new Card("Increasing Savagery", 'G', 4, 'S'));
        dataList.add(new Card("Increasing Vengeance", 'R', 2, 'I'));
        dataList.add(new Card("Indomitable Archangel", 'W', 4, 'C'));
        dataList.add(new Card("Inexorable Tide", 'U', 5, 'E'));
        dataList.add(new Card("Infernal Plunge", 'R', 1, 'S'));
        dataList.add(new Card("Inferno Titan", 'R', 6, 'C'));
        dataList.add(new Card("Infiltration Lens", 'A', 1, 'A'));
        dataList.add(new Card("Inkmoth Nexus", 'N', 0, 'L'));
        dataList.add(new Card("Inquisitor Exarch", 'W', 2, 'C'));
        dataList.add(new Card("Inquisitor's Flail", 'A', 2, 'A'));
        dataList.add(new Card("Insatiable Souleater", 'A', 4, 'C'));
        dataList.add(new Card("Instigator Gang/Wildblood Pack", 'R', 4, 'C'));
        dataList.add(new Card("Instill Infection", 'B', 4, 'I'));
        dataList.add(new Card("Intangible Virtue", 'W', 2, 'E'));
        dataList.add(new Card("Into the Core", 'R', 4, 'I'));
        dataList.add(new Card("Into the Maw of Hell", 'R', 6, 'S'));
        dataList.add(new Card("Invader Parasite", 'R', 5, 'C'));
        dataList.add(new Card("Invisible Stalker", 'U', 2, 'C'));
        dataList.add(new Card("Iron Myr", 'A', 2, 'C'));
        dataList.add(new Card("Island", 'N', 0, 'L'));
        dataList.add(new Card("Isolated Chapel", 'N', 0, 'L'));
        dataList.add(new Card("Isolation Cell", 'A', 4, 'A'));
        dataList.add(new Card("Jace,  Memory Adept", 'U', 5, 'P'));
        dataList.add(new Card("Jace's Archivist", 'U', 3, 'C'));
        dataList.add(new Card("Jace's Erasure", 'U', 2, 'E'));
        dataList.add(new Card("Jade Mage", 'G', 2, 'C'));
        dataList.add(new Card("Jar of Eyeballs", 'A', 3, 'A'));
        dataList.add(new Card("Jin-Gitaxias,  Core Augur", 'U', 10, 'C'));
        dataList.add(new Card("Jor Kadeen,  the Prevailer", 'M', 5, 'C'));
        dataList.add(new Card("Karn Liberated", 'A', 7, 'P'));
        dataList.add(new Card("Kemba,  Kha Regent", 'W', 3, 'C'));
        dataList.add(new Card("Kemba's Legion", 'W', 7, 'C'));
        dataList.add(new Card("Kemba's Skyguard", 'W', 3, 'C'));
        dataList.add(new Card("Kessig Cagebreakers", 'G', 5, 'C'));
        dataList.add(new Card("Kessig Recluse", 'G', 4, 'C'));
        dataList.add(new Card("Kessig Wolf", 'R', 3, 'C'));
        dataList.add(new Card("Kessig Wolf Run", 'N', 0, 'L'));
        dataList.add(new Card("Kiln Walker", 'A', 3, 'C'));
        dataList.add(new Card("Kindercatch", 'G', 6, 'C'));
        dataList.add(new Card("Kite Shield", 'A', 0, 'A'));
        dataList.add(new Card("Knowledge Pool", 'A', 6, 'A'));
        dataList.add(new Card("Koth of the Hammer", 'R', 4, 'P'));
        dataList.add(new Card("Koth's Courier", 'R', 3, 'C'));
        dataList.add(new Card("Kraken's Eye", 'A', 2, 'A'));
        dataList.add(new Card("Kruin Outlaw/Terror of Kruin Pass", 'R', 3, 'C'));
        dataList.add(new Card("Kuldotha Flamefiend", 'R', 6, 'C'));
        dataList.add(new Card("Kuldotha Forgemaster", 'A', 5, 'C'));
        dataList.add(new Card("Kuldotha Phoenix", 'R', 5, 'C'));
        dataList.add(new Card("Kuldotha Rebirth", 'R', 1, 'S'));
        dataList.add(new Card("Kuldotha Ringleader", 'R', 5, 'C'));
        dataList.add(new Card("Laboratory Maniac", 'U', 3, 'C'));
        dataList.add(new Card("Lambholt Elder/Silverpelt Werewolf", 'G', 3, 'C'));
        dataList.add(new Card("Lantern Spirit", 'U', 3, 'C'));
        dataList.add(new Card("Lashwrithe", 'A', 4, 'A'));
        dataList.add(new Card("Lava Axe", 'R', 5, 'S'));
        dataList.add(new Card("Lead the Stampede", 'G', 3, 'S'));
        dataList.add(new Card("Leaden Myr", 'A', 2, 'C'));
        dataList.add(new Card("Leeching Bite", 'G', 2, 'I'));
        dataList.add(new Card("Leonin Arbiter", 'W', 2, 'C'));
        dataList.add(new Card("Leonin Relic-Warder", 'W', 2, 'C'));
        dataList.add(new Card("Leonin Skyhunter", 'W', 2, 'C'));
        dataList.add(new Card("Levitation", 'U', 4, 'E'));
        dataList.add(new Card("Liege of the Tangle", 'G', 8, 'C'));
        dataList.add(new Card("Lifelink", 'W', 1, 'E'));
        dataList.add(new Card("Life's Finale", 'B', 6, 'S'));
        dataList.add(new Card("Lifesmith", 'G', 2, 'C'));
        dataList.add(new Card("Lightning Elemental", 'R', 4, 'C'));
        dataList.add(new Card("Liliana of the Veil", 'B', 3, 'P'));
        dataList.add(new Card("Lingering Souls", 'W', 3, 'S'));
        dataList.add(new Card("Liquimetal Coating", 'A', 2, 'A'));
        dataList.add(new Card("Livewire Lash", 'A', 2, 'A'));
        dataList.add(new Card("Llanowar Elves", 'G', 1, 'C'));
        dataList.add(new Card("Lord of the Unreal", 'U', 2, 'C'));
        dataList.add(new Card("Lost in the Mist", 'U', 5, 'I'));
        dataList.add(new Card("Lost in the Woods", 'G', 5, 'E'));
        dataList.add(new Card("Lost Leonin", 'W', 2, 'C'));
        dataList.add(new Card("Loxodon Convert", 'W', 4, 'C'));
        dataList.add(new Card("Loxodon Partisan", 'W', 5, 'C'));
        dataList.add(new Card("Loxodon Wayfarer", 'W', 3, 'C'));
        dataList.add(new Card("Loyal Cathar/Unhallowed Cathar", 'M', 2, 'C'));
        dataList.add(new Card("Ludevic's Test Subject/Ludevic's Abomination", 'U', 2, 'C'));
        dataList.add(new Card("Lumberknot", 'G', 4, 'C'));
        dataList.add(new Card("Lumengrid Drake", 'U', 4, 'C'));
        dataList.add(new Card("Lumengrid Gargoyle", 'A', 6, 'C'));
        dataList.add(new Card("Lure", 'G', 3, 'E'));
        dataList.add(new Card("Lurking Crocodile", 'G', 3, 'C'));
        dataList.add(new Card("Lux Cannon", 'A', 4, 'A'));
        dataList.add(new Card("Magnetic Mine", 'A', 4, 'A'));
        dataList.add(new Card("Make a Wish", 'G', 4, 'S'));
        dataList.add(new Card("Makeshift Mauler", 'U', 4, 'C'));
        dataList.add(new Card("Mana Leak", 'U', 2, 'I'));
        dataList.add(new Card("Manabarbs", 'R', 4, 'E'));
        dataList.add(new Card("Manalith", 'A', 3, 'A'));
        dataList.add(new Card("Manic Vandal", 'R', 3, 'C'));
        dataList.add(new Card("Manor Gargoyle", 'A', 5, 'C'));
        dataList.add(new Card("Manor Skeleton", 'B', 2, 'C'));
        dataList.add(new Card("Markov Blademaster", 'R', 3, 'C'));
        dataList.add(new Card("Markov Patrician", 'B', 3, 'C'));
        dataList.add(new Card("Markov Warlord", 'R', 6, 'C'));
        dataList.add(new Card("Marrow Shards", 'W', 1, 'I'));
        dataList.add(new Card("Mask of Avacyn", 'A', 2, 'A'));
        dataList.add(new Card("Massacre Wurm", 'B', 6, 'C'));
        dataList.add(new Card("Master Splicer", 'W', 4, 'C'));
        dataList.add(new Card("Master Thief", 'U', 4, 'C'));
        dataList.add(new Card("Master's Call", 'W', 3, 'I'));
        dataList.add(new Card("Maul Splicer", 'G', 7, 'C'));
        dataList.add(new Card("Mausoleum Guard", 'W', 4, 'C'));
        dataList.add(new Card("Maw of the Mire", 'B', 5, 'S'));
        dataList.add(new Card("Mayor of Avabruck/Howlpack Alpha", 'G', 2, 'C'));
        dataList.add(new Card("Melira,  Sylvok Outcast", 'G', 2, 'C'));
        dataList.add(new Card("Melira's Keepers", 'G', 5, 'C'));
        dataList.add(new Card("Melt Terrain", 'R', 4, 'S'));
        dataList.add(new Card("Memnite", 'A', 0, 'C'));
        dataList.add(new Card("Memoricide", 'B', 4, 'S'));
        dataList.add(new Card("Memory's Journey", 'U', 2, 'I'));
        dataList.add(new Card("Mental Misstep", 'U', 1, 'I'));
        dataList.add(new Card("Mentor of the Meek", 'W', 3, 'C'));
        dataList.add(new Card("Merfolk Looter", 'U', 2, 'C'));
        dataList.add(new Card("Merfolk Mesmerist", 'U', 2, 'C'));
        dataList.add(new Card("Mesa Enchantress", 'W', 3, 'C'));
        dataList.add(new Card("Metallic Mastery", 'R', 3, 'S'));
        dataList.add(new Card("Midnight Guard", 'W', 3, 'C'));
        dataList.add(new Card("Midnight Haunting", 'W', 3, 'I'));
        dataList.add(new Card("Mighty Leap", 'W', 2, 'I'));
        dataList.add(new Card("Mikaeus,  the Lunarch", 'W', 1, 'C'));
        dataList.add(new Card("Mikaeus,  the Unhallowed", 'B', 6, 'C'));
        dataList.add(new Card("Mimic Vat", 'A', 3, 'A'));
        dataList.add(new Card("Mind Control", 'U', 5, 'E'));
        dataList.add(new Card("Mind Rot", 'B', 3, 'S'));
        dataList.add(new Card("Mind Unbound", 'U', 6, 'E'));
        dataList.add(new Card("Mindcrank", 'A', 2, 'A'));
        dataList.add(new Card("Mindculling", 'U', 6, 'S'));
        dataList.add(new Card("Mindshrieker", 'U', 2, 'C'));
        dataList.add(new Card("Mindslaver", 'A', 6, 'A'));
        dataList.add(new Card("Mirran Crusader", 'W', 3, 'C'));
        dataList.add(new Card("Mirran Mettle", 'G', 1, 'I'));
        dataList.add(new Card("Mirran Spy", 'U', 3, 'C'));
        dataList.add(new Card("Mirror-Mad Phantasm", 'U', 5, 'C'));
        dataList.add(new Card("Mirrorworks", 'A', 5, 'A'));
        dataList.add(new Card("Mitotic Manipulation", 'U', 3, 'S'));
        dataList.add(new Card("Moan of the Unhallowed", 'B', 4, 'S'));
        dataList.add(new Card("Molder Beast", 'G', 5, 'C'));
        dataList.add(new Card("Moldgraf Monstrosity", 'G', 7, 'C'));
        dataList.add(new Card("Molten Psyche", 'R', 3, 'S'));
        dataList.add(new Card("Moltensteel Dragon", 'R', 6, 'C'));
        dataList.add(new Card("Molten-Tail Masticore", 'A', 4, 'C'));
        dataList.add(new Card("Moment of Heroism", 'W', 2, 'I'));
        dataList.add(new Card("Mondronen Shaman/Tovolar's Magehunter", 'R', 4, 'C'));
        dataList.add(new Card("Monomania", 'B', 5, 'S'));
        dataList.add(new Card("Moon Heron", 'U', 4, 'C'));
        dataList.add(new Card("Moonmist", 'G', 2, 'I'));
        dataList.add(new Card("Moonveil Dragon", 'R', 6, 'C'));
        dataList.add(new Card("Moorland Haunt", 'N', 0, 'L'));
        dataList.add(new Card("Morbid Plunder", 'B', 3, 'S'));
        dataList.add(new Card("Moriok Reaver", 'B', 3, 'C'));
        dataList.add(new Card("Moriok Replica", 'A', 3, 'C'));
        dataList.add(new Card("Morkrut Banshee", 'B', 5, 'C'));
        dataList.add(new Card("Mortarpod", 'A', 2, 'A'));
        dataList.add(new Card("Mortis Dogs", 'B', 4, 'C'));
        dataList.add(new Card("Mountain", 'N', 0, 'L'));
        dataList.add(new Card("Mox Opal", 'A', 0, 'A'));
        dataList.add(new Card("Mulch", 'G', 2, 'S'));
        dataList.add(new Card("Murder of Crows", 'U', 5, 'C'));
        dataList.add(new Card("Mutagenic Growth", 'G', 1, 'I'));
        dataList.add(new Card("Mycosynth Fiend", 'G', 3, 'C'));
        dataList.add(new Card("Mycosynth Wellspring", 'A', 2, 'A'));
        dataList.add(new Card("Myr Battlesphere", 'A', 7, 'C'));
        dataList.add(new Card("Myr Galvanizer", 'A', 3, 'C'));
        dataList.add(new Card("Myr Propagator", 'A', 3, 'C'));
        dataList.add(new Card("Myr Reservoir", 'A', 3, 'A'));
        dataList.add(new Card("Myr Sire", 'A', 2, 'C'));
        dataList.add(new Card("Myr Superion", 'A', 2, 'C'));
        dataList.add(new Card("Myr Turbine", 'A', 5, 'A'));
        dataList.add(new Card("Myr Welder", 'A', 3, 'C'));
        dataList.add(new Card("Myrsmith", 'W', 2, 'C'));
        dataList.add(new Card("Mystic Retrieval", 'U', 4, 'S'));
        dataList.add(new Card("Naturalize", 'G', 2, 'I'));
        dataList.add(new Card("Naturalize", 'G', 2, 'I'));
        dataList.add(new Card("Nearheath Stalker", 'R', 5, 'C'));
        dataList.add(new Card("Necrogen Censer", 'A', 3, 'A'));
        dataList.add(new Card("Necrogen Scudder", 'B', 3, 'C'));
        dataList.add(new Card("Necropede", 'A', 2, 'C'));
        dataList.add(new Card("Necropouncer", 'A', 6, 'A'));
        dataList.add(new Card("Necrotic Ooze", 'B', 4, 'C'));
        dataList.add(new Card("Negate", 'U', 2, 'I'));
        dataList.add(new Card("Nephalia Drownyard", 'N', 0, 'L'));
        dataList.add(new Card("Nephalia Seakite", 'U', 4, 'C'));
        dataList.add(new Card("Nested Ghoul", 'B', 5, 'C'));
        dataList.add(new Card("Neurok Commando", 'U', 3, 'C'));
        dataList.add(new Card("Neurok Invisimancer", 'U', 3, 'C'));
        dataList.add(new Card("Neurok Replica", 'A', 3, 'C'));
        dataList.add(new Card("Nevermore", 'W', 3, 'E'));
        dataList.add(new Card("Niblis of the Breath", 'U', 3, 'C'));
        dataList.add(new Card("Niblis of the Mist", 'W', 3, 'C'));
        dataList.add(new Card("Niblis of the Urn", 'W', 2, 'C'));
        dataList.add(new Card("Night Revelers", 'R', 5, 'C'));
        dataList.add(new Card("Night Terrors", 'B', 3, 'S'));
        dataList.add(new Card("Nightbird's Clutches", 'R', 2, 'S'));
        dataList.add(new Card("Nihil Spellbomb", 'A', 1, 'A'));
        dataList.add(new Card("Nim Deathmantle", 'A', 2, 'A'));
        dataList.add(new Card("Norn's Annex", 'W', 5, 'A'));
        dataList.add(new Card("Noxious Revival", 'G', 1, 'I'));
        dataList.add(new Card("Numbing Dose", 'U', 5, 'E'));
        dataList.add(new Card("Oblivion Ring", 'W', 3, 'E'));
        dataList.add(new Card("Oculus", 'U', 2, 'C'));
        dataList.add(new Card("Ogre Geargrabber", 'R', 6, 'C'));
        dataList.add(new Card("Ogre Menial", 'R', 4, 'C'));
        dataList.add(new Card("Ogre Resister", 'R', 4, 'C'));
        dataList.add(new Card("Olivia Voldaren", 'M', 4, 'C'));
        dataList.add(new Card("Omen Machine", 'A', 6, 'A'));
        dataList.add(new Card("One-Eyed Scarecrow", 'A', 3, 'C'));
        dataList.add(new Card("Onyx Mage", 'B', 2, 'C'));
        dataList.add(new Card("Orchard Spirit", 'G', 3, 'C'));
        dataList.add(new Card("Origin Spellbomb", 'A', 1, 'A'));
        dataList.add(new Card("Overrun", 'G', 5, 'S'));
        dataList.add(new Card("Oxidda Daredevil", 'R', 2, 'C'));
        dataList.add(new Card("Oxidda Scrapmelter", 'R', 4, 'C'));
        dataList.add(new Card("Pacifism", 'W', 2, 'E'));
        dataList.add(new Card("Painful Quandary", 'B', 5, 'E'));
        dataList.add(new Card("Painsmith", 'B', 2, 'C'));
        dataList.add(new Card("Palladium Myr", 'A', 3, 'C'));
        dataList.add(new Card("Panic Spellbomb", 'A', 1, 'A'));
        dataList.add(new Card("Parallel Lives", 'G', 4, 'E'));
        dataList.add(new Card("Paraselene", 'W', 3, 'S'));
        dataList.add(new Card("Parasitic Implant", 'B', 4, 'E'));
        dataList.add(new Card("Past in Flames", 'R', 4, 'S'));
        dataList.add(new Card("Peace Strider", 'A', 4, 'C'));
        dataList.add(new Card("Pentavus", 'A', 7, 'C'));
        dataList.add(new Card("Peregrine Griffin", 'W', 5, 'C'));
        dataList.add(new Card("Perilous Myr", 'A', 2, 'C'));
        dataList.add(new Card("Personal Sanctuary", 'W', 3, 'E'));
        dataList.add(new Card("Pestilent Souleater", 'A', 5, 'C'));
        dataList.add(new Card("Phantasmal Bear", 'U', 1, 'C'));
        dataList.add(new Card("Phantasmal Dragon", 'U', 4, 'C'));
        dataList.add(new Card("Phantasmal Image", 'U', 2, 'C'));
        dataList.add(new Card("Phyresis", 'B', 2, 'E'));
        dataList.add(new Card("Phyrexian Crusader", 'B', 3, 'C'));
        dataList.add(new Card("Phyrexian Digester", 'A', 3, 'C'));
        dataList.add(new Card("Phyrexian Hulk", 'A', 6, 'C'));
        dataList.add(new Card("Phyrexian Hydra", 'G', 5, 'C'));
        dataList.add(new Card("Phyrexian Ingester", 'U', 7, 'C'));
        dataList.add(new Card("Phyrexian Juggernaut", 'A', 6, 'C'));
        dataList.add(new Card("Phyrexian Metamorph", 'U', 4, 'C'));
        dataList.add(new Card("Phyrexian Obliterator", 'B', 4, 'C'));
        dataList.add(new Card("Phyrexian Rager", 'B', 3, 'C'));
        dataList.add(new Card("Phyrexian Rebirth", 'W', 6, 'S'));
        dataList.add(new Card("Phyrexian Revoker", 'A', 2, 'C'));
        dataList.add(new Card("Phyrexian Swarmlord", 'G', 6, 'C'));
        dataList.add(new Card("Phyrexian Unlife", 'W', 3, 'E'));
        dataList.add(new Card("Phyrexian Vatmother", 'B', 4, 'C'));
        dataList.add(new Card("Phyrexia's Core", 'N', 0, 'L'));
        dataList.add(new Card("Pierce Strider", 'A', 4, 'C'));
        dataList.add(new Card("Piston Sledge", 'A', 3, 'A'));
        dataList.add(new Card("Pistus Strike", 'G', 3, 'I'));
        dataList.add(new Card("Pitchburn Devils", 'R', 5, 'C'));
        dataList.add(new Card("Pith Driller", 'B', 5, 'C'));
        dataList.add(new Card("Plague Myr", 'A', 2, 'C'));
        dataList.add(new Card("Plague Stinger", 'B', 2, 'C'));
        dataList.add(new Card("Plaguemaw Beast", 'G', 5, 'C'));
        dataList.add(new Card("Plains", 'N', 0, 'L'));
        dataList.add(new Card("Plated Seastrider", 'U', 2, 'C'));
        dataList.add(new Card("Platinum Emperion", 'A', 8, 'C'));
        dataList.add(new Card("Plummet", 'G', 2, 'I'));
        dataList.add(new Card("Ponder", 'U', 1, 'S'));
        dataList.add(new Card("Porcelain Legionnaire", 'W', 3, 'C'));
        dataList.add(new Card("Postmortem Lunge", 'B', 1, 'S'));
        dataList.add(new Card("Praetor's Counsel", 'G', 8, 'S'));
        dataList.add(new Card("Praetor's Grasp", 'B', 3, 'S'));
        dataList.add(new Card("Precursor Golem", 'A', 5, 'C'));
        dataList.add(new Card("Predator Ooze", 'G', 3, 'C'));
        dataList.add(new Card("Prey Upon", 'G', 1, 'S'));
        dataList.add(new Card("Pride Guardian", 'W', 1, 'C'));
        dataList.add(new Card("Priest of Urabrask", 'R', 3, 'C'));
        dataList.add(new Card("Priests of Norn", 'W', 3, 'C'));
        dataList.add(new Card("Primeval Titan", 'G', 6, 'C'));
        dataList.add(new Card("Primordial Hydra", 'G', 2, 'C'));
        dataList.add(new Card("Pristine Talisman", 'A', 3, 'A'));
        dataList.add(new Card("Prototype Portal", 'A', 4, 'A'));
        dataList.add(new Card("Psychic Barrier", 'U', 2, 'I'));
        dataList.add(new Card("Psychic Miasma", 'B', 2, 'S'));
        dataList.add(new Card("Psychic Surgery", 'U', 2, 'E'));
        dataList.add(new Card("Psychosis Crawler", 'A', 5, 'C'));
        dataList.add(new Card("Puresteel Paladin", 'W', 2, 'C'));
        dataList.add(new Card("Purify the Grave", 'W', 1, 'I'));
        dataList.add(new Card("Putrefax", 'G', 5, 'C'));
        dataList.add(new Card("Pyreheart Wolf", 'R', 3, 'C'));
        dataList.add(new Card("Quicksilver Amulet", 'A', 4, 'A'));
        dataList.add(new Card("Quicksilver Gargantuan", 'U', 7, 'C'));
        dataList.add(new Card("Quicksilver Geyser", 'U', 5, 'I'));
        dataList.add(new Card("Quilled Slagwurm", 'G', 7, 'C'));
        dataList.add(new Card("Rage Extractor", 'R', 5, 'A'));
        dataList.add(new Card("Rage Thrower", 'R', 6, 'C'));
        dataList.add(new Card("Rakish Heir", 'R', 3, 'C'));
        dataList.add(new Card("Rally the Forces", 'R', 3, 'I'));
        dataList.add(new Card("Rally the Peasants", 'W', 3, 'I'));
        dataList.add(new Card("Rampant Growth", 'G', 2, 'S'));
        dataList.add(new Card("Ranger's Guile", 'G', 1, 'I'));
        dataList.add(new Card("Ratchet Bomb", 'A', 2, 'A'));
        dataList.add(new Card("Ravenous Demon/Archdemon of Greed", 'B', 5, 'C'));
        dataList.add(new Card("Ray of Revelation", 'W', 2, 'I'));
        dataList.add(new Card("Razor Hippogriff", 'W', 5, 'C'));
        dataList.add(new Card("Razor Swine", 'R', 3, 'C'));
        dataList.add(new Card("Razorfield Rhino", 'A', 6, 'C'));
        dataList.add(new Card("Razorfield Thresher", 'A', 7, 'C'));
        dataList.add(new Card("Razorverge Thicket", 'N', 0, 'L'));
        dataList.add(new Card("Reap the Seagraf", 'B', 3, 'S'));
        dataList.add(new Card("Reaper from the Abyss", 'B', 6, 'C'));
        dataList.add(new Card("Reaper of Sheoldred", 'B', 5, 'C'));
        dataList.add(new Card("Reassembling Skeleton", 'B', 2, 'C'));
        dataList.add(new Card("Rebuke", 'W', 3, 'I'));
        dataList.add(new Card("Reckless Waif/Merciless Predator", 'R', 1, 'C'));
        dataList.add(new Card("Reclaim", 'G', 1, 'I'));
        dataList.add(new Card("Red Sun's Zenith", 'R', 1, 'S'));
        dataList.add(new Card("Redirect", 'U', 2, 'I'));
        dataList.add(new Card("Relentless Skaabs", 'U', 5, 'C'));
        dataList.add(new Card("Relic Putrescence", 'B', 3, 'E'));
        dataList.add(new Card("Remember the Fallen", 'W', 3, 'S'));
        dataList.add(new Card("Requiem Angel", 'W', 6, 'C'));
        dataList.add(new Card("Reverberate", 'R', 2, 'I'));
        dataList.add(new Card("Revoke Existence", 'W', 2, 'S'));
        dataList.add(new Card("Riddlesmith", 'U', 2, 'C'));
        dataList.add(new Card("Riot Devils", 'R', 3, 'C'));
        dataList.add(new Card("Rites of Flourishing", 'G', 3, 'E'));
        dataList.add(new Card("Roc Egg", 'W', 3, 'C'));
        dataList.add(new Card("Rolling Temblor", 'R', 3, 'S'));
        dataList.add(new Card("Rooftop Storm", 'U', 6, 'E'));
        dataList.add(new Card("Rootbound Crag", 'N', 0, 'L'));
        dataList.add(new Card("Rot Wolf", 'G', 3, 'C'));
        dataList.add(new Card("Rotted Hystrix", 'G', 5, 'C'));
        dataList.add(new Card("Rotting Fensnake", 'B', 4, 'C'));
        dataList.add(new Card("Royal Assassin", 'B', 3, 'C'));
        dataList.add(new Card("Runechanter's Pike", 'A', 2, 'A'));
        dataList.add(new Card("Runeclaw Bear", 'G', 2, 'C'));
        dataList.add(new Card("Rune-Scarred Demon", 'B', 7, 'C'));
        dataList.add(new Card("Runic Repetition", 'U', 3, 'S'));
        dataList.add(new Card("Russet Wolves", 'R', 4, 'C'));
        dataList.add(new Card("Rust Tick", 'A', 3, 'C'));
        dataList.add(new Card("Rusted Relic", 'A', 4, 'A'));
        dataList.add(new Card("Rusted Sentinel", 'A', 4, 'C'));
        dataList.add(new Card("Rusted Slasher", 'A', 4, 'C'));
        dataList.add(new Card("Ruthless Invasion", 'R', 4, 'S'));
        dataList.add(new Card("Saberclaw Golem", 'A', 5, 'C'));
        dataList.add(new Card("Sacred Wolf", 'G', 3, 'C'));
        dataList.add(new Card("Salvage Scout", 'W', 1, 'C'));
        dataList.add(new Card("Sanctuary Cat", 'W', 1, 'C'));
        dataList.add(new Card("Sangromancer", 'B', 4, 'C'));
        dataList.add(new Card("Saving Grasp", 'U', 1, 'I'));
        dataList.add(new Card("Scepter of Empires", 'A', 3, 'A'));
        dataList.add(new Card("Scorch the Fields", 'R', 5, 'S'));
        dataList.add(new Card("Scoria Elemental", 'R', 5, 'C'));
        dataList.add(new Card("Scorned Villager/Moonscarred Werewolf", 'G', 2, 'C'));
        dataList.add(new Card("Scourge of Geier Reach", 'R', 5, 'C'));
        dataList.add(new Card("Scourge Servant", 'B', 5, 'C'));
        dataList.add(new Card("Scrambleverse", 'R', 8, 'S'));
        dataList.add(new Card("Scrapdiver Serpent", 'U', 7, 'C'));
        dataList.add(new Card("Scrapyard Salvo", 'R', 3, 'S'));
        dataList.add(new Card("Screeching Bat/Stalking Vampire", 'B', 3, 'C'));
        dataList.add(new Card("Screeching Silcaw", 'U', 2, 'C'));
        dataList.add(new Card("Screeching Skaab", 'U', 2, 'C'));
        dataList.add(new Card("Seachrome Coast", 'N', 0, 'L'));
        dataList.add(new Card("Seance", 'W', 4, 'E'));
        dataList.add(new Card("Secrets of the Dead", 'U', 3, 'E'));
        dataList.add(new Card("Seize the Initiative", 'W', 1, 'I'));
        dataList.add(new Card("Selfless Cathar", 'W', 1, 'C'));
        dataList.add(new Card("Selhoff Occultist", 'U', 3, 'C'));
        dataList.add(new Card("Semblance Anvil", 'A', 3, 'A'));
        dataList.add(new Card("Sengir Vampire", 'B', 5, 'C'));
        dataList.add(new Card("Sensor Splicer", 'W', 5, 'C'));
        dataList.add(new Card("Sensory Deprivation", 'U', 1, 'E'));
        dataList.add(new Card("Septic Rats", 'B', 3, 'C'));
        dataList.add(new Card("Serra Angel", 'W', 5, 'C'));
        dataList.add(new Card("Serum Raker", 'U', 4, 'C'));
        dataList.add(new Card("Sever the Bloodline", 'B', 4, 'S'));
        dataList.add(new Card("Shape Anew", 'U', 4, 'S'));
        dataList.add(new Card("Sharpened Pitchfork", 'A', 2, 'A'));
        dataList.add(new Card("Shatter", 'R', 2, 'I'));
        dataList.add(new Card("Shattered Angel", 'W', 5, 'C'));
        dataList.add(new Card("Shattered Perception", 'R', 3, 'S'));
        dataList.add(new Card("Sheoldred, Whispering One", 'B', 7, 'C'));
        dataList.add(new Card("Shimmer Myr", 'A', 3, 'C'));
        dataList.add(new Card("Shimmering Grotto", 'N', 0, 'L'));
        dataList.add(new Card("Shock", 'R', 1, 'I'));
        dataList.add(new Card("Shriek Raptor", 'W', 5, 'C'));
        dataList.add(new Card("Shriekgeist", 'U', 2, 'C'));
        dataList.add(new Card("Shriekhorn", 'A', 1, 'A'));
        dataList.add(new Card("Shrine of Boundless Growth", 'A', 3, 'A'));
        dataList.add(new Card("Shrine of Burning Rage", 'A', 2, 'A'));
        dataList.add(new Card("Shrine of Limitless Power", 'A', 3, 'A'));
        dataList.add(new Card("Shrine of Loyal Legions", 'A', 2, 'A'));
        dataList.add(new Card("Shrine of Piercing Vision", 'A', 2, 'A'));
        dataList.add(new Card("Sickleslicer", 'A', 3, 'A'));
        dataList.add(new Card("Siege Mastodon", 'W', 5, 'C'));
        dataList.add(new Card("Sightless Ghoul", 'B', 4, 'C'));
        dataList.add(new Card("Signal Pest", 'A', 1, 'C'));
        dataList.add(new Card("Silent Departure", 'U', 1, 'S'));
        dataList.add(new Card("Silver Myr", 'A', 2, 'C'));
        dataList.add(new Card("Silverchase Fox", 'W', 2, 'C'));
        dataList.add(new Card("Silverclaw Griffin", 'W', 5, 'C'));
        dataList.add(new Card("Silver-Inlaid Dagger", 'A', 1, 'A'));
        dataList.add(new Card("Silverskin Armor", 'A', 2, 'A'));
        dataList.add(new Card("Skaab Goliath", 'U', 6, 'C'));
        dataList.add(new Card("Skaab Ruinator", 'U', 3, 'C'));
        dataList.add(new Card("Skeletal Grimace", 'B', 2, 'E'));
        dataList.add(new Card("Skillful Lunge", 'W', 2, 'I'));
        dataList.add(new Card("Skinrender", 'B', 4, 'C'));
        dataList.add(new Card("Skinshifter", 'G', 2, 'C'));
        dataList.add(new Card("Skinwing", 'A', 4, 'A'));
        dataList.add(new Card("Skirsdag Cultist", 'R', 4, 'C'));
        dataList.add(new Card("Skirsdag Flayer", 'B', 2, 'C'));
        dataList.add(new Card("Skirsdag High Priest", 'B', 2, 'C'));
        dataList.add(new Card("Skithiryx,  the Blight Dragon", 'B', 5, 'C'));
        dataList.add(new Card("Sky-Eel School", 'U', 5, 'C'));
        dataList.add(new Card("Skywinder Drake", 'U', 3, 'C'));
        dataList.add(new Card("Slag Fiend", 'R', 1, 'C'));
        dataList.add(new Card("Slagstorm", 'R', 3, 'S'));
        dataList.add(new Card("Slash Panther", 'R', 5, 'C'));
        dataList.add(new Card("Slaughter Cry", 'R', 3, 'I'));
        dataList.add(new Card("Slayer of the Wicked", 'W', 4, 'C'));
        dataList.add(new Card("Slice in Twain", 'G', 4, 'I'));
        dataList.add(new Card("Smallpox", 'B', 2, 'S'));
        dataList.add(new Card("Smite the Monstrous", 'W', 4, 'I'));
        dataList.add(new Card("Snapcaster Mage", 'U', 2, 'C'));
        dataList.add(new Card("Snapsail Glider", 'A', 3, 'C'));
        dataList.add(new Card("Solemn Simulacrum", 'A', 4, 'C'));
        dataList.add(new Card("Soliton", 'A', 5, 'C'));
        dataList.add(new Card("Somberwald Dryad", 'G', 2, 'C'));
        dataList.add(new Card("Somberwald Spider", 'G', 5, 'C'));
        dataList.add(new Card("Sorin Markov", 'B', 6, 'P'));
        dataList.add(new Card("Sorin, Lord of Innistrad", 'M', 4, 'P'));
        dataList.add(new Card("Sorin's Thirst", 'B', 2, 'I'));
        dataList.add(new Card("Sorin's Vengeance", 'B', 7, 'S'));
        dataList.add(new Card("Soul Conduit", 'A', 6, 'A'));
        dataList.add(new Card("Soul Parry", 'W', 2, 'I'));
        dataList.add(new Card("Soul Seizer/Ghastly Haunting", 'U', 5, 'C'));
        dataList.add(new Card("Spare from Evil", 'W', 2, 'I'));
        dataList.add(new Card("Spectral Flight", 'U', 2, 'E'));
        dataList.add(new Card("Spectral Rider", 'W', 2, 'C'));
        dataList.add(new Card("Spellskite", 'A', 2, 'C'));
        dataList.add(new Card("Sphere of the Suns", 'A', 2, 'A'));
        dataList.add(new Card("Sphinx of Uthuun", 'U', 7, 'C'));
        dataList.add(new Card("Spider Spawning", 'G', 5, 'S'));
        dataList.add(new Card("Spidery Grasp", 'G', 3, 'I'));
        dataList.add(new Card("Spikeshot Elder", 'R', 1, 'C'));
        dataList.add(new Card("Spin Engine", 'A', 3, 'C'));
        dataList.add(new Card("Spine of Ish Sah", 'A', 7, 'A'));
        dataList.add(new Card("Spinebiter", 'G', 6, 'C'));
        dataList.add(new Card("Spined Thopter", 'U', 3, 'C'));
        dataList.add(new Card("Spiraling Duelist", 'R', 4, 'C'));
        dataList.add(new Card("Spire Monitor", 'U', 5, 'C'));
        dataList.add(new Card("Spire Serpent", 'U', 5, 'C'));
        dataList.add(new Card("Spirit Mantle", 'W', 2, 'E'));
        dataList.add(new Card("Spiteful Shadows", 'B', 2, 'E'));
        dataList.add(new Card("Splinterfright", 'G', 3, 'C'));
        dataList.add(new Card("Spread the Sickness", 'B', 5, 'S'));
        dataList.add(new Card("Stampeding Rhino", 'G', 5, 'C'));
        dataList.add(new Card("Stave Off", 'W', 1, 'I'));
        dataList.add(new Card("Steady Progress", 'U', 3, 'I'));
        dataList.add(new Card("Steel Hellkite", 'A', 6, 'C'));
        dataList.add(new Card("Steel Sabotage", 'U', 1, 'I'));
        dataList.add(new Card("Stensia Bloodhall", 'N', 0, 'L'));
        dataList.add(new Card("Stingerfling Spider", 'G', 5, 'C'));
        dataList.add(new Card("Stitched Drake", 'U', 3, 'C'));
        dataList.add(new Card("Stitcher's Apprentice", 'U', 2, 'C'));
        dataList.add(new Card("Stoic Rebuttal", 'U', 3, 'I'));
        dataList.add(new Card("Stonehorn Dignitary", 'W', 4, 'C'));
        dataList.add(new Card("Stony Silence", 'W', 2, 'E'));
        dataList.add(new Card("Stormblood Berserker", 'R', 2, 'C'));
        dataList.add(new Card("Stormbound Geist", 'U', 3, 'C'));
        dataList.add(new Card("Stormfront Pegasus", 'W', 2, 'C'));
        dataList.add(new Card("Strandwalker", 'A', 5, 'A'));
        dataList.add(new Card("Strangleroot Geist", 'G', 2, 'C'));
        dataList.add(new Card("Strata Scythe", 'A', 3, 'A'));
        dataList.add(new Card("Strider Harness", 'A', 3, 'A'));
        dataList.add(new Card("Stromkirk Captain", 'M', 3, 'C'));
        dataList.add(new Card("Stromkirk Noble", 'R', 1, 'C'));
        dataList.add(new Card("Stromkirk Patrol", 'B', 5, 'C'));
        dataList.add(new Card("Sturmgeist", 'U', 5, 'C'));
        dataList.add(new Card("Sudden Disappearance", 'W', 6, 'S'));
        dataList.add(new Card("Sulfur Falls", 'N', 0, 'L'));
        dataList.add(new Card("Sun Titan", 'W', 6, 'C'));
        dataList.add(new Card("Sunblast Angel", 'W', 6, 'C'));
        dataList.add(new Card("Sundial of the Infinite", 'A', 2, 'A'));
        dataList.add(new Card("Sunpetal Grove", 'N', 0, 'L'));
        dataList.add(new Card("Sunspear Shikari", 'W', 2, 'C'));
        dataList.add(new Card("Surge Node", 'A', 1, 'A'));
        dataList.add(new Card("Surgical Extraction", 'B', 1, 'I'));
        dataList.add(new Card("Suture Priest", 'W', 2, 'C'));
        dataList.add(new Card("Sutured Ghoul", 'B', 7, 'C'));
        dataList.add(new Card("Swamp", 'N', 0, 'L'));
        dataList.add(new Card("Swiftfoot Boots", 'A', 2, 'A'));
        dataList.add(new Card("Sword of Body and Mind", 'A', 3, 'A'));
        dataList.add(new Card("Sword of Feast and Famine", 'A', 3, 'A'));
        dataList.add(new Card("Sword of War and Peace", 'A', 3, 'A'));
        dataList.add(new Card("Sylvok Lifestaff", 'A', 1, 'A'));
        dataList.add(new Card("Sylvok Replica", 'A', 3, 'C'));
        dataList.add(new Card("Tainted Strike", 'B', 1, 'I'));
        dataList.add(new Card("Talons of Falkenrath", 'R', 2, 'E'));
        dataList.add(new Card("Tangle Angler", 'G', 4, 'C'));
        dataList.add(new Card("Tangle Hulk", 'A', 5, 'C'));
        dataList.add(new Card("Tangle Mantis", 'G', 4, 'C'));
        dataList.add(new Card("Taste of Blood", 'B', 1, 'S'));
        dataList.add(new Card("Tectonic Rift", 'R', 4, 'S'));
        dataList.add(new Card("Tel-Jilad Defiance", 'G', 2, 'I'));
        dataList.add(new Card("Tel-Jilad Fallen", 'G', 4, 'C'));
        dataList.add(new Card("Tempered Steel", 'W', 3, 'E'));
        dataList.add(new Card("Tezzeret,  Agent of Bolas", 'M', 4, 'P'));
        dataList.add(new Card("Tezzeret's Gambit", 'U', 4, 'S'));
        dataList.add(new Card("Thalia,  Guardian of Thraben", 'W', 2, 'C'));
        dataList.add(new Card("Think Twice", 'U', 2, 'I'));
        dataList.add(new Card("Thopter Assembly", 'A', 6, 'C'));
        dataList.add(new Card("Thought Scour", 'U', 1, 'I'));
        dataList.add(new Card("Thraben Doomsayer", 'W', 3, 'C'));
        dataList.add(new Card("Thraben Heretic", 'W', 2, 'C'));
        dataList.add(new Card("Thraben Purebloods", 'W', 5, 'C'));
        dataList.add(new Card("Thraben Sentry/Thraben Militia", 'W', 4, 'C'));
        dataList.add(new Card("Thran Golem", 'A', 5, 'C'));
        dataList.add(new Card("Throne of Empires", 'A', 4, 'A'));
        dataList.add(new Card("Throne of Geth", 'A', 2, 'A'));
        dataList.add(new Card("Thrummingbird", 'U', 2, 'C'));
        dataList.add(new Card("Thrun,  the Last Troll", 'G', 4, 'C'));
        dataList.add(new Card("Thundering Tanadon", 'G', 6, 'C'));
        dataList.add(new Card("Time Reversal", 'U', 5, 'S'));
        dataList.add(new Card("Timely Reinforcements", 'W', 3, 'S'));
        dataList.add(new Card("Tine Shrike", 'W', 4, 'C'));
        dataList.add(new Card("Titan Forge", 'A', 3, 'A'));
        dataList.add(new Card("Titanic Growth", 'G', 2, 'I'));
        dataList.add(new Card("Torch Fiend", 'R', 2, 'C'));
        dataList.add(new Card("Tormented Pariah/Rampaging Werewolf", 'R', 4, 'C'));
        dataList.add(new Card("Tormented Soul", 'B', 1, 'C'));
        dataList.add(new Card("Tormentor Exarch", 'R', 4, 'C'));
        dataList.add(new Card("Torpor Orb", 'A', 2, 'A'));
        dataList.add(new Card("Tower Geist", 'U', 4, 'C'));
        dataList.add(new Card("Tower of Calamities", 'A', 4, 'A'));
        dataList.add(new Card("Toxic Nim", 'B', 6, 'C'));
        dataList.add(new Card("Tracker's Instincts", 'G', 2, 'S'));
        dataList.add(new Card("Tragic Slip", 'B', 1, 'I'));
        dataList.add(new Card("Training Drone", 'A', 3, 'C'));
        dataList.add(new Card("Traitorous Blood", 'R', 3, 'S'));
        dataList.add(new Card("Travel Preparations", 'G', 2, 'S'));
        dataList.add(new Card("Traveler's Amulet", 'A', 1, 'A'));
        dataList.add(new Card("Treasure Mage", 'U', 3, 'C'));
        dataList.add(new Card("Tree of Redemption", 'G', 4, 'C'));
        dataList.add(new Card("Trepanation Blade", 'A', 3, 'A'));
        dataList.add(new Card("Trespassing Souleater", 'A', 3, 'C'));
        dataList.add(new Card("Tribute to Hunger", 'B', 3, 'I'));
        dataList.add(new Card("Trigon of Corruption", 'A', 4, 'A'));
        dataList.add(new Card("Trigon of Infestation", 'A', 4, 'A'));
        dataList.add(new Card("Trigon of Mending", 'A', 2, 'A'));
        dataList.add(new Card("Trigon of Rage", 'A', 2, 'A'));
        dataList.add(new Card("Trigon of Thought", 'A', 5, 'A'));
        dataList.add(new Card("Trinket Mage", 'U', 3, 'C'));
        dataList.add(new Card("Triumph of the Hordes", 'G', 4, 'S'));
        dataList.add(new Card("Trollhide", 'G', 3, 'E'));
        dataList.add(new Card("True Conviction", 'W', 6, 'E'));
        dataList.add(new Card("Tumble Magnet", 'A', 3, 'A'));
        dataList.add(new Card("Tunnel Ignus", 'R', 2, 'C'));
        dataList.add(new Card("Turn Aside", 'U', 1, 'I'));
        dataList.add(new Card("Turn the Tide", 'U', 2, 'I'));
        dataList.add(new Card("Turn to Frog", 'U', 2, 'I'));
        dataList.add(new Card("Turn to Slag", 'R', 5, 'S'));
        dataList.add(new Card("Twisted Image", 'U', 1, 'I'));
        dataList.add(new Card("Typhoid Rats", 'B', 1, 'C'));
        dataList.add(new Card("Ulvenwald Bear", 'G', 3, 'C'));
        dataList.add(new Card("Ulvenwald Mystics/Ulvenwald Primordials", 'G', 4, 'C'));
        dataList.add(new Card("Unbreathing Horde", 'B', 3, 'C'));
        dataList.add(new Card("Unburial Rites", 'B', 5, 'S'));
        dataList.add(new Card("Undead Alchemist", 'U', 4, 'C'));
        dataList.add(new Card("Undying Evil", 'B', 1, 'I'));
        dataList.add(new Card("Unnatural Predation", 'G', 1, 'I'));
        dataList.add(new Card("Unruly Mob", 'W', 2, 'C'));
        dataList.add(new Card("Unsummon", 'U', 1, 'I'));
        dataList.add(new Card("Untamed Might", 'G', 1, 'I'));
        dataList.add(new Card("Unwinding Clock", 'A', 4, 'A'));
        dataList.add(new Card("Urabrask the Hidden", 'R', 5, 'C'));
        dataList.add(new Card("Urgent Exorcism", 'W', 2, 'I'));
        dataList.add(new Card("Vampire Interloper", 'B', 2, 'C'));
        dataList.add(new Card("Vampire Outcasts", 'B', 4, 'C'));
        dataList.add(new Card("Vampiric Fury", 'R', 2, 'I'));
        dataList.add(new Card("Vapor Snag", 'U', 1, 'I'));
        dataList.add(new Card("Vastwood Gorger", 'G', 6, 'C'));
        dataList.add(new Card("Vault of the Archangel", 'N', 0, 'L'));
        dataList.add(new Card("Vault Skirge", 'B', 2, 'C'));
        dataList.add(new Card("Vault Skyward", 'U', 1, 'I'));
        dataList.add(new Card("Vector Asp", 'A', 1, 'C'));
        dataList.add(new Card("Vedalken Anatomist", 'U', 3, 'C'));
        dataList.add(new Card("Vedalken Certarch", 'U', 1, 'C'));
        dataList.add(new Card("Vedalken Infuser", 'U', 4, 'C'));
        dataList.add(new Card("Vengeful Pharaoh", 'B', 5, 'C'));
        dataList.add(new Card("Vengeful Vampire", 'B', 6, 'C'));
        dataList.add(new Card("Venser, the Sojourner", 'M', 5, 'P'));
        dataList.add(new Card("Venser's Journal", 'A', 5, 'A'));
        dataList.add(new Card("Victim of Night", 'B', 2, 'I'));
        dataList.add(new Card("Victorious Destruction", 'R', 5, 'S'));
        dataList.add(new Card("Victory's Herald", 'W', 6, 'C'));
        dataList.add(new Card("Vigil for the Lost", 'W', 4, 'E'));
        dataList.add(new Card("Village Bell-Ringer", 'W', 3, 'C'));
        dataList.add(new Card("Village Cannibals", 'B', 3, 'C'));
        dataList.add(new Card("Village Ironsmith/Ironfang", 'R', 2, 'C'));
        dataList.add(new Card("Village Survivors", 'G', 5, 'C'));
        dataList.add(new Card("Villagers of Estwald/Howlpack of Estwald", 'G', 3, 'C'));
        dataList.add(new Card("Viral Drake", 'U', 4, 'C'));
        dataList.add(new Card("Viridian Betrayers", 'G', 3, 'C'));
        dataList.add(new Card("Viridian Claw", 'A', 2, 'A'));
        dataList.add(new Card("Viridian Corrupter", 'G', 3, 'C'));
        dataList.add(new Card("Viridian Emissary", 'G', 2, 'C'));
        dataList.add(new Card("Viridian Harvest", 'G', 1, 'E'));
        dataList.add(new Card("Viridian Revel", 'G', 3, 'E'));
        dataList.add(new Card("Virulent Wound", 'B', 1, 'I'));
        dataList.add(new Card("Visions of Beyond", 'U', 1, 'I'));
        dataList.add(new Card("Vital Splicer", 'G', 4, 'C'));
        dataList.add(new Card("Vivisection", 'U', 4, 'S'));
        dataList.add(new Card("Voiceless Spirit", 'W', 3, 'C'));
        dataList.add(new Card("Volcanic Dragon", 'R', 6, 'C'));
        dataList.add(new Card("Volition Reins", 'U', 6, 'E'));
        dataList.add(new Card("Volt Charge", 'R', 3, 'I'));
        dataList.add(new Card("Vorapede", 'G', 5, 'C'));
        dataList.add(new Card("Vorinclex,  Voice of Hunger", 'G', 8, 'C'));
        dataList.add(new Card("Vulshok Heartstoker", 'R', 3, 'C'));
        dataList.add(new Card("Vulshok Refugee", 'R', 3, 'C'));
        dataList.add(new Card("Vulshok Replica", 'A', 3, 'C'));
        dataList.add(new Card("Wakedancer", 'B', 3, 'C'));
        dataList.add(new Card("Walking Corpse", 'B', 2, 'C'));
        dataList.add(new Card("Wall of Tanglecord", 'A', 2, 'C'));
        dataList.add(new Card("Wall of Torches", 'R', 2, 'C'));
        dataList.add(new Card("War Report", 'W', 4, 'I'));
        dataList.add(new Card("Warden of the Wall", 'A', 3, 'A'));
        dataList.add(new Card("Warpath Ghoul", 'B', 3, 'C'));
        dataList.add(new Card("Warstorm Surge", 'R', 6, 'E'));
        dataList.add(new Card("Whipflare", 'R', 2, 'S'));
        dataList.add(new Card("Whispering Specter", 'B', 3, 'C'));
        dataList.add(new Card("White Sun's Zenith", 'W', 3, 'I'));
        dataList.add(new Card("Whitesun's Passage", 'W', 2, 'I'));
        dataList.add(new Card("Wild Hunger", 'G', 3, 'I'));
        dataList.add(new Card("Wing Puncture", 'G', 1, 'I'));
        dataList.add(new Card("Wing Splicer", 'U', 4, 'C'));
        dataList.add(new Card("Witchbane Orb", 'A', 4, 'A'));
        dataList.add(new Card("Withstand Death", 'G', 1, 'I'));
        dataList.add(new Card("Wolfbitten Captive/Krallenhorde Killer", 'G', 1, 'C'));
        dataList.add(new Card("Wolfhunter's Quiver", 'A', 1, 'A'));
        dataList.add(new Card("Wooden Stake", 'A', 2, 'A'));
        dataList.add(new Card("Woodland Cemetery", 'N', 0, 'L'));
        dataList.add(new Card("Woodland Sleuth", 'G', 4, 'C'));
        dataList.add(new Card("Worldslayer", 'A', 5, 'A'));
        dataList.add(new Card("Wrack with Madness", 'R', 4, 'S'));
        dataList.add(new Card("Wreath of Geists", 'G', 1, 'E'));
        dataList.add(new Card("Wring Flesh", 'B', 1, 'I'));
        dataList.add(new Card("Wurmcoil Engine", 'A', 6, 'C'));
        dataList.add(new Card("Wurm's Tooth", 'A', 2, 'A'));
        dataList.add(new Card("Xenograft", 'U', 5, 'E'));
        dataList.add(new Card("Young Wolf", 'G', 1, 'C'));
        dataList.add(new Card("Zombie Apocalypse", 'B', 6, 'S'));
        dataList.add(new Card("Zombie Goliath", 'B', 5, 'C'));
        dataList.add(new Card("Zombie Infestation", 'B', 2, 'E'));
    }

    // ----------------------------------------------------------
    /**
     * Returns the Card with specified name if found.
     * @param name the String name of the card
     * @return null if not found
     */
    public Card find(String name)
    {
       int results = search(name, 0, 1080);
       if (results >= 0)
       {
           return dataList.get(results);
       }
       return null;
    }

    /**
     * Simple recursive alphabetical binary search of the database.
     * @param toFind name to look for
     * @param first index to start with
     * @param last index to end with
     * @return -1 if not found/invalid, index of the card if found
     */
    private int search(String toFind, int first, int last)
    {
        if (first > last)
        {
            return -1;
        }
        else
        {
            int middle = (first + last) / 2;
            int compResult = compare(toFind, dataList.get(middle).getName());
            if (compResult == 0)
            {
                return middle;
            }
            else if(compResult == -1)
            {
                return search(toFind, first, middle - 1);
            }
            else if(compResult == 1)
            {
                return search(toFind, middle + 1, last);
            }
        }
        return -1;
    }

    /**
     * Compares two strings for equality. Used by the search to reposition the
     * index.
     * @param nameA name being looked for
     * @param nameb name being compared to
     * @return 0 if equal, 1 if higher on alpha, -1 if lower, 2 if never found
     */
    private int compare(String nameA, String nameB)
    {
        char activeA;
        char activeB;
        String nameAS = fixString(nameA);
        String nameBS = fixString(nameB);
        if (nameAS == nameBS)
        {
            return 0;
        }
        for (int i = 0; i < nameAS.length(); i++)
        {
             activeA = nameAS.charAt(i);
             activeB = nameBS.charAt(i);
             if (activeA < activeB)
             {
                 return -1;
             }
             else if (activeA > activeB)
             {
                 return 1;
             }
        }
        return 2;
    }

    /**
     * Removes all non-alpha characters from a string (a-z only)
     * @param badString String pre-fix
     * @return String post-fix
     */
    private String fixString(String badString)
    {
        String oldString = badString.toLowerCase();
        StringBuffer newString = new StringBuffer();
        for (int i = 0; i < badString.length(); i++)
        {
            if (122 >= oldString.charAt(i) && oldString.charAt(i) >= 97)
            {
                newString.append(badString.charAt(i));
            }
        }
        return newString.toString();
    }
}
